# Generated by Django 2.2.17 on 2020-12-30 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(help_text='角色名，最多64个字符', max_length=64, unique=True, verbose_name='角色名'),
        ),
    ]
