# Generated by Django 2.2.17 on 2020-12-31 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtsapp', '0003_auto_20201231_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='working',
            name='approve_time',
            field=models.DateTimeField(blank=True, default=None, help_text='审批通过时间', null=True),
        ),
    ]
