# Generated by Django 2.2.17 on 2020-12-31 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtsapp', '0004_auto_20201231_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='opetationlog',
            name='operation_name',
            field=models.CharField(blank=True, default='', help_text='修改人', max_length=32, null=True, verbose_name='修改人'),
        ),
    ]
