# Generated by Django 2.2.17 on 2021-01-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtsapp', '0005_opetationlog_operation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskpro',
            name='creator',
            field=models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='任务创建者'),
        ),
    ]
