# Generated by Django 2.2.17 on 2021-01-06 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wtsapp', '0006_taskpro_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskpro',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='wtsapp.TaskPro'),
        ),
    ]
