# Generated by Django 2.2.17 on 2021-01-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtsapp', '0007_auto_20210106_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskpro',
            name='task_process',
            field=models.CharField(default='', help_text='任务进度，0-100', max_length=2, verbose_name='任务进度'),
        ),
    ]
