# Generated by Django 2.2.17 on 2021-01-06 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtsapp', '0009_auto_20210106_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskpro',
            name='task_info',
            field=models.CharField(default='', max_length=1024, verbose_name='任务内容'),
        ),
    ]
