# Generated by Django 2.2.17 on 2021-01-06 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wtsapp', '0010_taskpro_task_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskpro',
            name='parent',
        ),
        migrations.AddField(
            model_name='taskpro',
            name='parent_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='wtsapp.TaskPro'),
        ),
    ]
