# Generated by Django 2.2.17 on 2021-01-06 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wtsapp', '0011_auto_20210106_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskpro',
            name='parent_id',
        ),
        migrations.AddField(
            model_name='taskpro',
            name='parent',
            field=models.ForeignKey(blank=True, db_column='parent_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='wtsapp.TaskPro'),
        ),
    ]
