# Generated by Django 2.2.17 on 2021-01-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtsapp', '0013_auto_20210106_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='working',
            name='approveor',
            field=models.CharField(blank=True, default='', help_text='审批人', max_length=32, null=True),
        ),
    ]
