# Generated by Django 2.2.17 on 2021-01-07 18:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtsapp', '0014_working_approveor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(db_index=True, default=None, max_length=11, null=True, validators=[django.core.validators.RegexValidator('^1[3456789][0-9]{9}$', '请输入正确的手机号码。')]),
        ),
    ]
